name: Lint
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install linter
        run: |
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s latest
          sudo mv ./bin/golangci-lint /usr/local/bin/
      - name: Run linter
        run: golangci-lint run
